server:
  port: 8080

# local
---
spring:
  profiles:
    active: local # 기본 환경 선택
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://motive-maria.cyatzgxa7cgf.ap-northeast-2.rds.amazonaws.com:3306/motive
    username: motive
    password: dlakdrn2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

multipart:
  maxFileSiz: 10MB
  maxRequestSize: 20MB

wording:
  image:
    path: ./images/wording/
